[0m18:56:03.490916 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab506c790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360fd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360ffd0>]}


============================== 18:56:03.496860 | 532a63d4-b3f0-477a-8f94-e1e0d1171c9e ==============================
[0m18:56:03.496860 [info ] [MainThread]: Running with dbt=1.8.9
[0m18:56:03.498061 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:56:03.507313 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/vscode/.dbt')}
[0m18:56:03.507779 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:56:58.683192 [debug] [MainThread]: Starter project path: /home/vscode/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m18:56:58.688455 [info ] [MainThread]: 
Your new dbt project "demo_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:56:58.689390 [info ] [MainThread]: Setting up your profile.
[0m18:58:25.367914 [error] [MainThread]: Encountered an error:
list index out of range
[0m18:58:25.369272 [error] [MainThread]: Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/home/vscode/.local/lib/python3.10/site-packages/dbt/task/init.py", line 244, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m18:58:25.371052 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 141.9283, "process_in_blocks": "416", "process_kernel_time": 0.135953, "process_mem_max_rss": "86180", "process_out_blocks": "80", "process_user_time": 1.151561}
[0m18:58:25.371895 [debug] [MainThread]: Command `dbt init` failed at 18:58:25.371751 after 141.93 seconds
[0m18:58:25.372405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab506c790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360fd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8ab360f550>]}
[0m18:58:25.372900 [debug] [MainThread]: Flushing usage events
[0m19:26:07.296676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e52aa14730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd3d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd3d90>]}


============================== 19:26:07.300900 | c8c8f341-9242-4c16-ae9f-3c50b0b3795f ==============================
[0m19:26:07.300900 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:26:07.301613 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:26:07.302155 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:26:07.303453 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.06611618, "process_in_blocks": "61352", "process_kernel_time": 0.286527, "process_mem_max_rss": "85424", "process_out_blocks": "8", "process_user_time": 1.161191}
[0m19:26:07.304132 [debug] [MainThread]: Command `dbt test` failed at 19:26:07.304025 after 0.07 seconds
[0m19:26:07.304549 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e52aa14730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd3d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x72e528fd36d0>]}
[0m19:26:07.304995 [debug] [MainThread]: Flushing usage events
[0m19:44:52.387169 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7acf181147c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7acf166cbd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7acf166cbd90>]}


============================== 19:44:52.390046 | a4286d48-6082-4953-99f7-910890fd42fb ==============================
[0m19:44:52.390046 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:44:52.390697 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:44:52.391248 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:44:52.392170 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.05494599, "process_in_blocks": "0", "process_kernel_time": 0.119905, "process_mem_max_rss": "85792", "process_out_blocks": "8", "process_user_time": 1.135109}
[0m19:44:52.392818 [debug] [MainThread]: Command `dbt test` failed at 19:44:52.392712 after 0.06 seconds
[0m19:44:52.393272 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7acf181147c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7acf166cbd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7acf166cb6d0>]}
[0m19:44:52.393698 [debug] [MainThread]: Flushing usage events
[0m19:47:15.844548 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73a15b688730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73a159c3bd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73a159c3bd90>]}


============================== 19:47:15.848617 | cddb2de4-e1b5-4464-9d02-80f8dcbd6d9a ==============================
[0m19:47:15.848617 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:47:15.849525 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt test', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:47:15.850325 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:47:15.851559 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.08057065, "process_in_blocks": "0", "process_kernel_time": 0.151519, "process_mem_max_rss": "85612", "process_out_blocks": "8", "process_user_time": 1.204182}
[0m19:47:15.852457 [debug] [MainThread]: Command `dbt test` failed at 19:47:15.852317 after 0.08 seconds
[0m19:47:15.853106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73a15b688730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73a159c3bd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73a159c3b6d0>]}
[0m19:47:15.853744 [debug] [MainThread]: Flushing usage events
[0m19:47:51.050518 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7615ce1b07f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7615cc767d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7615cc767d60>]}


============================== 19:47:51.053148 | e97e0623-52c6-4a18-8045-03870bf9bb87 ==============================
[0m19:47:51.053148 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:47:51.053812 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:47:51.054336 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:47:51.055204 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.05150683, "process_in_blocks": "0", "process_kernel_time": 0.087923, "process_mem_max_rss": "85660", "process_out_blocks": "16", "process_user_time": 1.063069}
[0m19:47:51.055789 [debug] [MainThread]: Command `dbt test` failed at 19:47:51.055685 after 0.05 seconds
[0m19:47:51.056186 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7615ce1b07f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7615cc767d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7615cc7676a0>]}
[0m19:47:51.056584 [debug] [MainThread]: Flushing usage events
[0m17:55:57.763951 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873fe568730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873fcb27d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873fcb27d90>]}


============================== 17:55:57.823156 | f2c3629a-ef25-4ee2-ad63-630b4bc2d0ac ==============================
[0m17:55:57.823156 [info ] [MainThread]: Running with dbt=1.8.9
[0m17:55:57.824081 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test --select source.yml', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:55:57.824836 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:55:57.826197 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.15245663, "process_in_blocks": "70760", "process_kernel_time": 0.3827, "process_mem_max_rss": "85476", "process_out_blocks": "8", "process_user_time": 1.562694}
[0m17:55:57.826861 [debug] [MainThread]: Command `dbt test` failed at 17:55:57.826752 after 0.15 seconds
[0m17:55:57.827308 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873fe568730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873fcb27d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7873fcb276d0>]}
[0m17:55:57.827804 [debug] [MainThread]: Flushing usage events
[0m17:56:43.367504 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eba7891c730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eba76ecbd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eba76ecbd90>]}


============================== 17:56:43.370237 | 6371b6ed-1607-428b-b2d5-b5c93eadc48b ==============================
[0m17:56:43.370237 [info ] [MainThread]: Running with dbt=1.8.9
[0m17:56:43.370916 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test --select demo_dbt_project/models/source.yml', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:56:43.371455 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-waynetaketwo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:56:43.372442 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.066941544, "process_in_blocks": "0", "process_kernel_time": 0.304891, "process_mem_max_rss": "85724", "process_out_blocks": "16", "process_user_time": 1.454987}
[0m17:56:43.373153 [debug] [MainThread]: Command `dbt test` failed at 17:56:43.373006 after 0.07 seconds
[0m17:56:43.373702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eba7891c730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eba76ecbd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eba76ecb6d0>]}
[0m17:56:43.374331 [debug] [MainThread]: Flushing usage events
